# Generated by Django 4.2.7 on 2026-01-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_password_reset_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="biometric_device_id",
            field=models.CharField(
                blank=True,
                help_text="Device identifier for biometric login",
                max_length=255,
                null=True,
                verbose_name="Biyometrik Cihaz ID",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="biometric_enabled",
            field=models.BooleanField(default=False, verbose_name="Biyometrik Giriş"),
        ),
    ]
