# Generated by Django 4.2.7 on 2026-01-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_biometric_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategories",
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="campaign_tag",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Kampanya"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="model_code",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Model Kodu",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_cash",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Peşin Fiyat",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_list",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Liste Fiyatı",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ek Garanti Kodu"
            ),
        ),
    ]
