# Generated by Django 4.2.7 on 2026-01-06 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_category_parent_product_campaign_tag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Tarih")),
                (
                    "store_address",
                    models.TextField(
                        default="Beko Mağaza, Lefkoşa", verbose_name="Mağaza Adresi"
                    ),
                ),
                (
                    "store_lat",
                    models.DecimalField(
                        decimal_places=7,
                        default=35.1856,
                        max_digits=10,
                        verbose_name="Mağaza Enlemi",
                    ),
                ),
                (
                    "store_lng",
                    models.DecimalField(
                        decimal_places=7,
                        default=33.3823,
                        max_digits=10,
                        verbose_name="Mağaza Boylamı",
                    ),
                ),
                (
                    "total_distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Toplam Mesafe (km)",
                    ),
                ),
                (
                    "total_duration_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Toplam Süre (dk)"
                    ),
                ),
                (
                    "is_optimized",
                    models.BooleanField(default=False, verbose_name="Optimize Edildi"),
                ),
                ("optimized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Teslimat Rotası",
                "verbose_name_plural": "Teslimat Rotaları",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Adres"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="address_city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Şehir"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="address_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitude koordinatı",
                max_digits=10,
                null=True,
                verbose_name="Enlem",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="address_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitude koordinatı",
                max_digits=10,
                null=True,
                verbose_name="Boylam",
            ),
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_date", models.DateField(verbose_name="Teslimat Tarihi")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("assigned", "Rotaya Atandı"),
                            ("in_transit", "Yolda"),
                            ("delivered", "Teslim Edildi"),
                            ("cancelled", "İptal"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("address", models.TextField(verbose_name="Teslimat Adresi")),
                (
                    "address_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Enlem",
                    ),
                ),
                (
                    "address_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Boylam",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müşteri",
                    ),
                ),
                (
                    "product_ownership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="products.productownership",
                        verbose_name="Satın Alınan Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teslimat",
                "verbose_name_plural": "Teslimatlar",
                "ordering": ["delivery_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryRouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stop_order",
                    models.PositiveIntegerField(
                        help_text="0=Mağaza (başlangıç), 1,2,3...=Müşteriler",
                        verbose_name="Sıra",
                    ),
                ),
                (
                    "estimated_arrival",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Tahmini Varış"
                    ),
                ),
                (
                    "distance_from_previous_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Önceki Duraktan Mesafe (km)",
                    ),
                ),
                (
                    "duration_from_previous_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Önceki Duraktan Süre (dk)"
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_stops",
                        to="products.delivery",
                        verbose_name="Teslimat",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="products.deliveryroute",
                        verbose_name="Rota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rota Durağı",
                "verbose_name_plural": "Rota Durakları",
                "ordering": ["route", "stop_order"],
                "unique_together": {("route", "stop_order"), ("route", "delivery")},
            },
        ),
    ]
