# Generated by Django 4.2.7 on 2026-01-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_delivery_models"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "is_read"], name="notif_user_read_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["notification_type"], name="notif_type_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["created_at"], name="notif_created_idx"),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["status"], name="svcreq_status_idx"),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["customer", "status"], name="svcreq_cust_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["created_at"], name="svcreq_created_idx"),
        ),
    ]
