# Generated by Django 4.2 on 2026-01-08 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_installment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Oluşturma'), ('update', 'Güncelleme'), ('delete', 'Silme'), ('login', 'Giriş'), ('logout', 'Çıkış'), ('login_failed', 'Başarısız Giriş'), ('password_change', 'Şifre Değişikliği'), ('password_reset', 'Şifre Sıfırlama'), ('permission_change', 'Yetki Değişikliği'), ('export', 'Veri Dışa Aktarma'), ('api_access', 'API Erişimi'), ('bulk_operation', 'Toplu İşlem')], max_length=20, verbose_name='İşlem')),
                ('model_name', models.CharField(blank=True, help_text='Etkilenen modelin adı (örn: Product, Order)', max_length=100, null=True, verbose_name='Model Adı')),
                ('object_id', models.IntegerField(blank=True, help_text="Etkilenen nesnenin ID'si", null=True, verbose_name='Nesne ID')),
                ('object_repr', models.CharField(blank=True, help_text='Nesnenin string temsili', max_length=255, null=True, verbose_name='Nesne Temsili')),
                ('changes', models.JSONField(blank=True, help_text="{'field': [old_value, new_value]} formatında", null=True, verbose_name='Değişiklikler')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='İstek Yolu')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='HTTP Metodu')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Durum Kodu')),
                ('extra_data', models.JSONField(blank=True, help_text='İşleme özgü ek bilgiler', null=True, verbose_name='Ek Veri')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman Damgası')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Denetim Kaydı',
                'verbose_name_plural': 'Denetim Kayıtları',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action'], name='audit_user_action_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='audit_model_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address'], name='audit_ip_idx'),
        ),
    ]
