# Generated by Django 4.2.7 on 2026-01-14 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_depot_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Tutar')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peşinat')),
                ('installment_count', models.PositiveIntegerField(verbose_name='Taksit Sayısı')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='active', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'seller']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_installment_plans', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Taksit Planı',
                'verbose_name_plural': 'Taksit Planları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Taksit No')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('due_date', models.DateField(verbose_name='Vade Tarihi')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('customer_confirmed', 'Müşteri Onayladı'), ('paid', 'Ödendi'), ('overdue', 'Gecikmiş')], default='pending', max_length=20, verbose_name='Durum')),
                ('customer_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Müşteri Onay Zamanı')),
                ('admin_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Admin Onay Zamanı')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='products.installmentplan', verbose_name='Taksit Planı')),
            ],
            options={
                'verbose_name': 'Taksit',
                'verbose_name_plural': 'Taksitler',
                'ordering': ['plan', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Oluşturma'), ('update', 'Güncelleme'), ('delete', 'Silme'), ('login', 'Giriş'), ('logout', 'Çıkış'), ('login_failed', 'Başarısız Giriş'), ('password_change', 'Şifre Değişikliği'), ('password_reset', 'Şifre Sıfırlama'), ('permission_change', 'Yetki Değişikliği'), ('export', 'Veri Dışa Aktarma'), ('api_access', 'API Erişimi'), ('bulk_operation', 'Toplu İşlem')], max_length=20, verbose_name='İşlem')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Adı')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='Nesne ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nesne Temsili')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Değişiklikler')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman Damgası')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Denetim Kaydı',
                'verbose_name_plural': 'Denetim Kayıtları',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['customer', 'status'], name='instplan_cust_status_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['status'], name='instplan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['status'], name='inst_status_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['due_date'], name='inst_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['plan', 'status'], name='inst_plan_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('plan', 'installment_number')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action'], name='audit_user_action_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='audit_model_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_timestamp_idx'),
        ),
    ]
