# Generated by Django 4.2.7 on 2026-03-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_fix_delivery_role_limit_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicequeue',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'Yüksek Öncelik'), (2, 'Normal Öncelik'), (3, 'Düşük Öncelik')], default=2, help_text='Öncelik Seviyesi (1=Yüksek, 2=Normal, 3=Düşük)'),
        ),
    ]
