# Generated by Django 4.2 on 2026-03-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_merge_20260319_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='product_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='products.productassignment'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='product_ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='products.productownership'),
        ),
    ]
