# Generated by Django 4.2.7 on 2026-06-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_normalize_assignment_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='install_duration_min',
            field=models.PositiveIntegerField(default=0, help_text='Tek bir adet için ortalama kurulum süresi (dakika). Kurulum yoksa 0.', verbose_name='Kurulum Süresi (dk)'),
        ),
        migrations.AddField(
            model_name='category',
            name='requires_installation',
            field=models.BooleanField(default=False, help_text='Teslimat ekibi bu kategorideki ürünü kurar mı? (örn. çamaşır makinesi, buzdolabı)', verbose_name='Kurulum Gerektirir'),
        ),
    ]
